apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: frontend
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: mbrabaa2023/api-gateway:${DOCKER_TAG}
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: FRONTEND_URL
          value: "http://frontend-service:8080"  # Nom court car même namespace
        - name: PAIEMENT_SERVICE_URL
          value: "http://paiement-service:3002"
        - name: RESERVATION_SERVICE_URL
          value: "http://reservation-service:3004"
        - name: TRAJET_SERVICE_URL
          value: "http://trajet-service:3004"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
