apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: frontend
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8000          # Port interne du service
      targetPort: 8000    # Port du container
      nodePort: 30088     # Port exposé sur les nodes (optionnel: 30000-32767)
